### ISSUE TITLE
Alder Lake and Rocket Lake additions already exist

### ISSUE THREAD

**Issue by alyxferrari** [GopnikOutlanders/OpenCore-Install-Guide#3]
I don't mean to knock your work at all, but I assume this fork is eventually intended to be the basis of a pull request? If so, I already have a collection of pull requests fixing up the guide related to Rocket Lake and Alder Lake, including additions to the `Getting Started with ACPI` section.

dortania/OpenCore-Install-Guide#342
dortania/OpenCore-Install-Guide#343
dortania/Getting-Started-with-ACPI#73

**Comment by dreamwhite** [comment]
Thank you dude! We'll merge it asap

**Comment by YuiiiPTChan** [comment]
Hello, I reviewed both of your PRs in the main repository and I don't think we will merge them now, let us know when its complete.
We are currently working on a general update with complete stuff.
